[package]
name = "webvr"
version = "0.1.0"
authors = ["Imanol Fernandez <mortimergoro@gmail.com>"]

[features]
default = ["openvr", "mock"]
openvr = ["openvr_sys"]
mock = []

[dependencies]
log  = "0.3"
openvr_sys = { version = "1.0.2", optional = true }

[dev-dependencies]
# Only required to run examples
glium = "0.15"
cgmath = "0.12"
image = "0.10"